import { ArrowRight, Boxes, ChartNoAxesCombined, ClipboardCheck, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";

const features = [
  { icon: Boxes, title: "A living catalogue", text: "See what is ready to borrow, where it belongs, and who looks after it." },
  { icon: ClipboardCheck, title: "Simple handoffs", text: "Request, issue, return and track every loan in one clean flow." },
  { icon: ChartNoAxesCombined, title: "Useful oversight", text: "Spot overdue items and lending patterns before they become a problem." },
];

export default function Landing() {
  return <main className="landing min-h-screen overflow-hidden bg-[#fafbff] text-slate-900">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8">
      <div className="flex items-center gap-3 font-semibold"><span className="rounded-xl bg-indigo-700 p-2 text-white shadow-lg shadow-indigo-200"><Boxes size={19}/></span>Asset Lending</div>
      <div className="flex items-center gap-3"><Link className="px-3 py-2 text-sm font-medium text-slate-600 hover:text-indigo-700" to="/login">Log in</Link><Link className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-700" to="/signup">Create account</Link></div>
    </nav>
    <section className="relative mx-auto max-w-6xl px-5 pb-20 pt-16 text-center sm:px-8 lg:pb-28 lg:pt-24">
      <div className="absolute left-1/2 top-0 -z-0 h-96 w-96 -translate-x-1/2 rounded-full bg-indigo-200/50 blur-3xl"/>
      <div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white px-3 py-1.5 text-xs font-semibold text-indigo-700 shadow-sm"><ShieldCheck size={14}/>Shared assets, made simple</span><h1 className="mx-auto mt-6 max-w-4xl text-5xl font-semibold tracking-[-0.045em] text-slate-950 sm:text-6xl lg:text-7xl">A better rhythm for <span className="text-indigo-700">shared things.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Asset Lending brings people, equipment, and accountability together—so your team can spend less time chasing items and more time using them.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-700 px-5 py-3.5 text-sm font-semibold text-white shadow-xl shadow-indigo-200 transition hover:bg-indigo-800">Create an account <ArrowRight size={17}/></Link><Link to="/login" className="rounded-xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-semibold text-slate-700 hover:border-indigo-200 hover:text-indigo-700">I already have an account</Link></div></div>
      <div className="relative mx-auto mt-16 grid max-w-4xl overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-2xl shadow-indigo-950/10 md:grid-cols-[1.15fr_.85fr]"><div className="p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Today’s lending desk</p><div className="mt-6 flex items-end gap-3"><strong className="text-5xl tracking-tight">24</strong><span className="mb-1 text-sm text-slate-500">items currently out</span></div><div className="mt-7 space-y-3">{["Camera kit · due Friday", "Portable projector · ready to issue", "Audio recorder · returned today"].map((x,i) => <div key={x} className="flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${i===0 ? "bg-amber-400" : i===1 ? "bg-indigo-500" : "bg-emerald-500"}`}/>{x}</div>)}</div></div><div className="bg-slate-950 p-7 text-white"><UsersRound className="text-indigo-300"/><p className="mt-10 text-sm text-slate-400">Built for everyone</p><p className="mt-2 text-2xl font-semibold">Members borrow with clarity. Librarians manage with confidence.</p><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-3/4 rounded-full bg-gradient-to-r from-cyan-300 to-indigo-400"/></div><p className="mt-2 text-xs text-slate-400">75% of this week’s returns are complete</p></div></div>
    </section>
    <section className="border-t border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="text-center text-sm font-semibold text-indigo-700">Everything your lending desk needs</p><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(({icon: Icon, title, text}) => <article key={title} className="rounded-2xl border border-slate-100 p-6 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-200/60"><span className="inline-flex rounded-xl bg-indigo-50 p-3 text-indigo-700"><Icon size={21}/></span><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></div></section>
  </main>;
}
